name: Deploy Workbench site to Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name:  Install wasm-tools
        run: dotnet workload install wasm-tools
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Publish
        run: dotnet publish Kyiv/Kyiv.csproj -c Release -o release --verbosity normal
      - name: Change base-tag in index.html from / to KyivMachine
        run: sed -i 's/<base href="\/" \/>/<base href="\/KyivMachine\/" \/>/g' release/wwwroot/index.html
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./release/wwwroot

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4